### ISSUE TITLE
Issue installing from Github

### ISSUE THREAD

**Issue by zachcp** [clara-genomics/racon-gpu#5]
He Team Clara Genomics,

Thank you for your library/work! The installation instructions in the Readme.md led to an SSH-related permissions error ( i don't have ssh keys associated with `clara-genomics`).  However, changing the git target to use `https` fixes the problem.  Heres what works for me in case anyone else encounters the same problem:

```bash
# retrieve code
git clone --recursive --recurse-submodules  https://github.com/clara-genomics/racon-gpu.git
cd racon-gpu
git submodule deinit vendor/ClaraGenomicsAnalysis
rm -rf .git/modules/vendor/ClaraGenomicsAnalysis
git rm -f vendor/ClaraGenomicsAnalysis
git submodule add https://github.com/clara-genomics/ClaraGenomicsAnalysis.git vendor/ClaraGenomicsAnalysis
git submodule update --recursive --init

# and build it
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make

```

zach cp

**Comment by cgjosephlee** [comment]
Edit the url in this line https://github.com/clara-genomics/racon-gpu/blob/add-gpu-support/.gitmodules#L24 to 
`https://github.com/clara-genomics/ClaraGenomicsAnalysis`.

**Comment by vellamike** [comment]
Thank you for reporting this! It has now been fixed in https://github.com/clara-genomics/racon-gpu/pull/6
